// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHFaEEEwWHgeVM8K2yzV7egVANaz7_GiA',
    appId: '1:219423552400:android:ccae96b31b90587fec3915',
    messagingSenderId: '219423552400',
    projectId: 'mawed-ghaseel',
    storageBucket: 'mawed-ghaseel.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhNbPf-y4KyaUpyEYbZHOSRUMtfx4g8Jk',
    appId: '1:219423552400:ios:4a726d6ff2d0cc76ec3915',
    messagingSenderId: '219423552400',
    projectId: 'mawed-ghaseel',
    storageBucket: 'mawed-ghaseel.firebasestorage.app',
    iosBundleId: 'com.example.lamah',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVV8d5yiwUsyJdNLbWfQu7rcKH4KIxq1s',
    appId: '1:219423552400:web:b08b0fd82754f663ec3915',
    messagingSenderId: '219423552400',
    projectId: 'mawed-ghaseel',
    authDomain: 'mawed-ghaseel.firebaseapp.com',
    storageBucket: 'mawed-ghaseel.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhNbPf-y4KyaUpyEYbZHOSRUMtfx4g8Jk',
    appId: '1:219423552400:ios:4a726d6ff2d0cc76ec3915',
    messagingSenderId: '219423552400',
    projectId: 'mawed-ghaseel',
    storageBucket: 'mawed-ghaseel.firebasestorage.app',
    iosBundleId: 'com.example.lamah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVV8d5yiwUsyJdNLbWfQu7rcKH4KIxq1s',
    appId: '1:219423552400:web:cf01833c997ff619ec3915',
    messagingSenderId: '219423552400',
    projectId: 'mawed-ghaseel',
    authDomain: 'mawed-ghaseel.firebaseapp.com',
    storageBucket: 'mawed-ghaseel.firebasestorage.app',
  );
}
